#!/bin/sh
# chkconfig: 2345 20 80
# description: hdp-nfs3 startup script
# processname: hdp-nfs3
#/*
# * Licensed to the Apache Software Foundation (ASF) under one
# * or more contributor license agreements.  See the NOTICE file
# * distributed with this work for additional information
# * regarding copyright ownership.  The ASF licenses this file
# * to you under the Apache License, Version 2.0 (the
# * "License"); you may not use this file except in compliance
# * with the License.  You may obtain a copy of the License at
# *
# *     http://www.apache.org/licenses/LICENSE-2.0
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# */

RETVAL=0

HDP_PORTMAP_PID=/var/run/hadoop/root/hadoop-root-portmap.pid
HDP_NFS3_PID=/var/run/hadoop/hdfs/hadoop-hdfs-nfs3.pid

HADOOP_DAEMON_BIN=/usr/hdp/2.2.0.0-2041/hadoop/sbin/hadoop-daemon.sh

case "$1" in
   start)
      echo "============================="
      echo "Starting hdp-hfs3..."
      echo "============================="
      echo "Starting Portmapper:"
        $HADOOP_DAEMON_BIN start portmap
        sleep 2
      echo "Starting NFS3 Gateway:"
        su - hdfs $HADOOP_DAEMON_BIN start nfs3
        sleep 5
      ;;

  stop)
      echo "=================================="
      echo "Shutting down hdp-nfs3..."
      echo "=================================="
      echo "Stopping NFS3 Gateway:"
        su - hdfs $HADOOP_DAEMON_BIN stop nfs3
      echo "Stopping Portmapper:"
        $HADOOP_DAEMON_BIN stop portmap
        rm -f ${HDP_PORTMAP_PID} ${HDP_NFS3_PID}
      ;;

  restart|reload)
        $0 stop
        $0 start
        ;;

  status)
      echo "======================================="
      echo "Checking status of hdp-nfs3..."
      echo "======================================="
        if [ -f ${HDP_NFS3_PID} ]
        then
          eval "ps -ef | grep `cat ${HDP_NFS3_PID}` | grep -v grep" > /dev/null
          RETVAL=$?
          if [ $RETVAL -eq 0 ]
          then
                echo "NFS3 Gateway running with PID  "  `cat ${HDP_NFS3_PID}`
          elif [ $RETVAL -eq 1 ]
          then
                echo "NFS3 Gateway is not running."
                exit 1
          fi
        else
                echo "NFS3 Gateway is not running."
                exit 1
        fi
        if [ -f ${HDP_PORTMAP_PID} ]
        then
          eval "ps -ef | grep `cat ${HDP_PORTMAP_PID}` | grep -v grep" > /dev/null
          RETVAL=$?
          if [ $RETVAL -eq 0 ]
          then
                echo "Portmapper running with PID  "  `cat ${HDP_PORTMAP_PID}`
          elif [ $RETVAL -eq 1 ]
          then
                echo "Portmapper is not running."
                exit 1
          fi
        else
                echo "Portmapper is not running."
                exit 1
        fi
      ;;
  *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
esac

exit $RETVAL
